version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    build:
      context: .
    command: php artisan serve --host=0.0.0.0 --port=80
    ports:
      - 80:80
    volumes:
      - ./:/app
    depends_on:
      - db
